#
###################################
# Site wide configuration
####################################
#
title: bo_oki
email: bkbkgg@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://bookpark.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Python", "Django"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: bo_oki
  avatar: django-logo.png
  job: "Future Django Web Developer"
  bio: "A future backend developer who loves baseball."
  email: bkbkgg@gmail.com
  disqus-shortname: bo_oki
  twitter: #username
  facebook: bookpark
  google:
    plus: #username
    analytics: UA-108297572-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bookpark #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: bo_oki
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
