# Site settings
title:          bo_oki
description:    "초보 개발자 개발 블로그"
baseurl:        "/bookpark"
url:            "https://bookpark.github.io/"

# Author
author:
  name:         Booki Park
  url:          https://bookpark.github.io
  email:        bkbkgg@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Themes
remote_theme:   chesterhow/tale
